os: osx
osx_image: xcode8.3
language: swift
script:
- xcodebuild clean test -workspace FoodCheck.xcworkspace -scheme FoodCheckTest -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.1' CODE_SIGNING_REQUIRED=NO
