os: osx
osx_image: xcode8.3
language: swift
script:
- xcodebuild clean build test -workspace FoodCheck.xcworkspace -scheme FoodCheckTest -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3.1' CODE_SIGNING_REQUIRED=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
    slack: passcoding:VFYINiqpYIL4ei4NPjLgyq38
